path_file_publisher:
  ros__parameters:
    filepath: "./install/pure_pursuit/share/pure_pursuit/path_files/levine_rough_path.csv"
  
pure_pursuit:
  ros__parameters:
    lookahead_distance_m: 1.0
    max_longitudinal_velocity_ms: 1.0
    min_longitudinal_velocity_ms: 1.0
    map_frame: "map"
    car_frame: "ego_racecar/base_link" 
    # NOTE: This will likely be different on the physical robot, so make a
    # separate launch file just for the physical robot that references a
    # DIFFERENT parameter file. This file could be renamed to simulation_params,
    # and the other could just be params.yaml.
